"""make_product_fields_nullable

Revision ID: 055548099790
Revises: 
Create Date: 2026-05-16 09:46:50.561383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '055548099790'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'brand_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'subject_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'feedbacks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'supplier_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'wh',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'wh',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'supplier_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'supplier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'feedbacks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'subject_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
