"""add_tracking_fields

Revision ID: 57bb78034e84
Revises: 055548099790
Create Date: 2026-05-17 17:40:36.329197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57bb78034e84'
down_revision: Union[str, Sequence[str], None] = '055548099790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('track_interval', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('iterations_left', sa.Integer(), nullable=True))

    op.execute("UPDATE tasks SET iterations_left = 1 WHERE iterations_left IS NULL")

    op.alter_column('tasks', 'iterations_left', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'iterations_left')
    op.drop_column('tasks', 'track_interval')

    # ### end Alembic commands ###
